import type { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex("profile_routes").del();
  await knex("routes").del();

  // Inserts seed entries for routes
  const routes = await knex("routes").insert([
    // Public Routes (no authentication)
    {
      id: 1,
      name: "api_docs",
      path: "/api-docs",
      type: "frontend",
      method: null,
      description: "Documentação da API",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 2,
      name: "health_check",
      path: "/health",
      type: "api",
      method: "GET",
      description: "Health check endpoint",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 3,
      name: "auth_login",
      path: "/auth/login",
      type: "api",
      method: "POST",
      description: "Login de usuário",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 4,
      name: "auth_refresh",
      path: "/auth/refresh",
      type: "api",
      method: "POST",
      description: "Refresh token",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 5,
      name: "password_reset_request",
      path: "/user/password-reset/request",
      type: "api",
      method: "POST",
      description: "Solicitar reset de senha",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 6,
      name: "password_reset_verify",
      path: "/user/password-reset/verify",
      type: "api",
      method: "POST",
      description: "Verificar token de reset",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 7,
      name: "password_reset",
      path: "/user/password-reset/reset",
      type: "api",
      method: "POST",
      description: "Resetar senha",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 8,
      name: "invite_accept",
      path: "/invite/accept",
      type: "api",
      method: "POST",
      description: "Aceitar convite",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Protected Routes (require authentication)
    // Auth
    {
      id: 9,
      name: "auth_logout",
      path: "/auth/logout",
      type: "api",
      method: "POST",
      description: "Logout de usuário",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Invite
    {
      id: 10,
      name: "invite_create",
      path: "/invite",
      type: "api",
      method: "POST",
      description: "Criar convite",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Tenant
    {
      id: 11,
      name: "tenant_create",
      path: "/tenant",
      type: "api",
      method: "POST",
      description: "Criar tenant",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 12,
      name: "tenant_list",
      path: "/tenant",
      type: "api",
      method: "GET",
      description: "Listar tenants",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 13,
      name: "tenant_get",
      path: "/tenant/:id",
      type: "api",
      method: "GET",
      description: "Buscar tenant por ID",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 14,
      name: "tenant_update",
      path: "/tenant/:id",
      type: "api",
      method: "PATCH",
      description: "Atualizar tenant",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 15,
      name: "tenant_delete",
      path: "/tenant/:id",
      type: "api",
      method: "DELETE",
      description: "Deletar tenant",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 16,
      name: "tenant_add_user",
      path: "/tenant/:id/user",
      type: "api",
      method: "POST",
      description: "Adicionar usuário ao tenant",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 17,
      name: "tenant_remove_user",
      path: "/tenant/:id/user",
      type: "api",
      method: "DELETE",
      description: "Remover usuário do tenant",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Profile
    {
      id: 18,
      name: "profile_create",
      path: "/profile",
      type: "api",
      method: "POST",
      description: "Criar perfil",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 19,
      name: "profile_list",
      path: "/profile",
      type: "api",
      method: "GET",
      description: "Listar perfis",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 20,
      name: "profile_get",
      path: "/profile/:id",
      type: "api",
      method: "GET",
      description: "Buscar perfil por ID",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 21,
      name: "profile_update",
      path: "/profile/:id",
      type: "api",
      method: "PATCH",
      description: "Atualizar perfil",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 22,
      name: "profile_delete",
      path: "/profile/:id",
      type: "api",
      method: "DELETE",
      description: "Deletar perfil",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 23,
      name: "profile_add_user",
      path: "/profile/:id/user",
      type: "api",
      method: "POST",
      description: "Adicionar usuário ao perfil",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 24,
      name: "profile_remove_user",
      path: "/profile/:id/user",
      type: "api",
      method: "DELETE",
      description: "Remover usuário do perfil",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },

    // Route
    {
      id: 25,
      name: "route_create",
      path: "/route",
      type: "api",
      method: "POST",
      description: "Criar rota",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 26,
      name: "route_list",
      path: "/route",
      type: "api",
      method: "GET",
      description: "Listar rotas",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 27,
      name: "route_get",
      path: "/route/:id",
      type: "api",
      method: "GET",
      description: "Buscar rota por ID",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 28,
      name: "route_update",
      path: "/route/:id",
      type: "api",
      method: "PATCH",
      description: "Atualizar rota",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 29,
      name: "route_delete",
      path: "/route/:id",
      type: "api",
      method: "DELETE",
      description: "Deletar rota",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 30,
      name: "route_add_profile",
      path: "/route/:id/profile",
      type: "api",
      method: "POST",
      description: "Adicionar perfil à rota",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 31,
      name: "route_remove_profile",
      path: "/route/:id/profile",
      type: "api",
      method: "DELETE",
      description: "Remover perfil da rota",
      is_active: true,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ]).returning("id");

  // Link protected routes to admin profile (id: 1)
  // Routes from id 9 onwards are protected
  const protectedRouteIds = [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31];
  
  const profileRoutes = protectedRouteIds.map(routeId => ({
    profile_id: 1, // admin profile
    route_id: routeId,
    is_active: true,
    created_at: knex.fn.now(),
    updated_at: knex.fn.now(),
  }));

  await knex("profile_routes").insert(profileRoutes);
}
